### ISSUE TITLE
 GeoServer error: Resource must be part of a store 

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#210]
Randomly we get in this error that stops GeoServer.

This is the stacktrace:

nitialization of bean failed; nested exception is java.lang.RuntimeException: java.lang.IllegalArgumentException: Resource must be part of a store: java.lang.IllegalArgumentException: Resource must be part of a store at org.geoserver.catalog.impl.CatalogImpl.validate(CatalogImpl.java:368) at org.geoserver.catalog.impl.CatalogImpl.add(CatalogImpl.java:354) at org.geoserver.config.GeoServerLoader.readCatalog(GeoServerLoader.java:382) at org.geoserver.config.GeoServerLoader.readCatalog(GeoServerLoader.java:220)

Apparently the layers are being created using an uncorrect DataStoreInfoImpl

**Comment by capooti** [comment]
Until we figure out how to prevent the bug, here is what I am doing in such situations:

cd /mnt/sdp/opt/geonode/data/workspaces/geonode/wm_201703

grep -rli 'DataStoreInfoImpl--456d3192:15a88bf2ae5:-6cef' * | xargs -i@ sudo sed -i 's/DataStoreInfoImpl--456d3192:15a88bf2ae5:-6cef/DataStoreInfoImpl-461eb3dd:15a866a5fdb:-55a2/g' @

Then restart GeoServer.

**Comment by ingenieroariel** [comment]
I just got:

```
2017-04-04 15:35:16,031 ERROR [context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'downloadLauncherRestlet' defined in URL [file:/mnt/sdp/opt/tomcat/a/webapps/geoserver/WEB-INF/classes/applicationContext.xml]: Cannot resolve reference to bean 'catalog' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localWorkspaceCatalog' defined in URL [jar:file:/mnt/sdp/opt/tomcat/a/webapps/geoserver/WEB-INF/lib/main-2.3-SNAPSHOT.jar!/applicationContext.xml]: Cannot resolve reference to bean 'advertisedCatalog' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advertisedCatalog' defined in URL [jar:file:/mnt/sdp/opt/tomcat/a/webapps/geoserver/WEB-INF/lib/main-2.3-SNAPSHOT.jar!/applicationContext.xml]: Cannot resolve reference to bean 'secureCatalog' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accessRulesDao' defined in URL [jar:file:/mnt/sdp/opt/tomcat/a/webapps/geoserver/WEB-INF/lib/main-2.3-SNAPSHOT.jar!/applicationSecurityContext.xml]: Cannot resolve reference to bean 'rawCatalog' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rawCatalog' defined in URL [jar:file:/mnt/sdp/opt/tomcat/a/webapps/geoserver/WEB-INF/lib/main-2.3-SNAPSHOT.jar!/applicationContext.xml]: Initialization of bean failed; nested exception is java.lang.RuntimeException: java.lang.IllegalArgumentException: Resource must be part of a store
```

**Comment by capooti** [comment]
Doing what is described you should be able to fix it.

**Comment by ingenieroariel** [comment]
I disabled the following layers:
```
a_otros_hje    erqwer_nee              mancha_urbana_1995_ku6  mancha_urbana_2014_omd  seattle_104
base_4sg       mancha_urbana_1989_uw0  mancha_urbana_1999_fjb  mancha_urbana_2016_9jo  starbucks_u_at
  mancha_urbana_1991_nfz  mancha_urbana_2005_4z9  qweqwe_hy0
```
