### ISSUE TITLE
kml upload raises an error

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#489]
Unexpected exception [] expected val for type

**Comment by capooti** [comment]
same with geojson

**Comment by capooti** [comment]
error logged:

```
Error creating import session
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/upload.py", line 362, in save_step
    target_store=None
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/client.py", line 103, in upload_files
    session.upload_task(files, use_url, intial_opts)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 421, in upload_task
    tasks = parse_response( resp )
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 48, in parse_response
    return Task(resp['task'], parent=parent)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 72, in __init__
    self._bind_json(json)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 104, in _bind_json
    val = binding.binding(val, parent=self)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 72, in __init__
    self._bind_json(json)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 200, in _bind_json
    super(Target, self)._bind_json(repr)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 99, in _bind_json
    self._binding_failed('expected val for %s', binding.name)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/gsimporter/api.py", line 113, in _binding_failed
    raise BindingFailed('[%s] %s' % (type(self), msg % args))
BindingFailed: [<class 'gsimporter.api.Target'>] expected val for type
Unexpected error in upload step
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 648, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 190, in save_step_view
    time_presentation_reference_value=form.cleaned_data['time_presentation_reference_value']
  File "/home/ubuntu/geonode/geonode/upload/upload.py", line 402, in save_step
    raise e
BindingFailed: [<class 'gsimporter.api.Target'>] expected val for type
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 648, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 190, in save_step_view
    time_presentation_reference_value=form.cleaned_data['time_presentation_reference_value']
  File "/home/ubuntu/geonode/geonode/upload/upload.py", line 402, in save_step
    raise e
BindingFailed: [<class 'gsimporter.api.Target'>] expected val for type
```
