### ISSUE TITLE
Some maps fails to save because thumbnail generation raises an error

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#574]
Screenshot

![image](https://user-images.githubusercontent.com/812849/50112614-976f6080-020d-11e9-884b-d2264e8783da.png)

**Comment by capooti** [comment]
This is caused by one (or more) layers which is not correctly rendered by the GeoServer REST API. This will be fixed once we implement this: https://github.com/cga-harvard/geonode/issues/570
Otherwise, the map save feature is working.

**Comment by capooti** [comment]
As per my comment above: this is caused by problem with existing data which will be fixed with #570, so let's keep that open
You will see that some map correctly save some other not if they contains data wich are invalid in the GeoServer REST API
For example try to save a map with a new layer, it should work

**Comment by capooti** [comment]
I could reproduce this, by just adding the russian raster layer to an empty map and then saving it.
It looks like the map save is broken becuase of the thumbnail generation. I could return a blank image in these cases?

```
Traceback (most recent call last):
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/geonode/geonode/contrib/worldmap/wm_extra/views.py", line 356, in new_map_json_wm
    map_obj.update_from_viewer(body, context={'request': request, 'mapId': map_obj.id, 'map': map_obj})
  File "/home/ubuntu/geonode/geonode/maps/models.py", line 220, in update_from_viewer
    self.save()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/polymorphic/models.py", line 82, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/ubuntu/geonode/geonode/geoserver/signals.py", line 648, in geoserver_post_save_map
    create_gs_thumbnail(instance, overwrite=False, check_bbox=True)
  File "/home/ubuntu/geonode/geonode/geoserver/helpers.py", line 2037, in create_gs_thumbnail
    return implementation(instance, overwrite, check_bbox)
  File "/home/ubuntu/geonode/geonode/layers/utils.py", line 1027, in create_gs_thumbnail_geonode
    overwrite=overwrite, check_bbox=check_bbox)
  File "/home/ubuntu/geonode/geonode/layers/utils.py", line 974, in create_thumbnail
    image = _prepare_thumbnail_body_from_opts(request_body)
  File "/home/ubuntu/geonode/geonode/geoserver/helpers.py", line 1913, in _prepare_thumbnail_body_from_opts
    t_ll = mercantile.tile(bounds[0], bounds[1], zoom)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/mercantile/__init__.py", line 227, in tile
    "Y can not be computed for latitude {} radians".format(lat))
```

**Comment by capooti** [comment]
This is working properly for me now.
