### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one User -- it returned 2

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#89]
Internal Server Error: /maps/7694/ajax-permissions-emailTraceback (most recent call last):

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "./geonode/maps/views.py", line 2412, in ajax_map_permissions_by_email
    return ajax_map_permissions(request, mapid, True)

  File "./geonode/maps/views.py", line 598, in ajax_map_permissions
    set_map_permissions(map_obj, spec, use_email)

  File "./geonode/maps/views.py", line 539, in set_map_permissions
    user_obj = User.objects.get(email=useremail)

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(_args, *_kwargs)

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/db/models/query.py", line 368, in get
    % (self.model._meta.object_name, num, kwargs))

MultipleObjectsReturned: get() returned more than one User -- it returned 2! Lookup parameters were {'email': u''}

**Comment by mbertrand** [comment]
Likely caused by multiple users with blank emails (found two - lextest and lextest2) - added fake emails for both from the admin interface.

**Comment by capooti** [comment]
Yes that was my guess. Under which circumnstances they can have a blank emails? Maybe when they are creating the user from the admin, as lex did here?
