### ISSUE TITLE
Cannot edit user profile anymore

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#91]
We need to fix this urgently.
If a user try to edit the profile, there is this error:

Internal Server Error: /profiles/edit/Traceback (most recent call last):

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)

  File "./geonode/profile/views.py", line 78, in edit_profile
    assert False

AssertionError

**Comment by capooti** [comment]
this has been fixed.
