### ISSUE TITLE
SuspiciousOperation: Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#92]
Not sure why this is happening, but we may need to figure out:

Internal Server Error: /Traceback (most recent call last):

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/middleware/common.py", line 55, in process_request
    host = request.get_host()

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/http/**init**.py", line 223, in get_host
    "Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): %s" % host)

SuspiciousOperation: Invalid HTTP_HOST header (you may need to set ALLOWED_HOSTS): 184.73.229.41

**Comment by capooti** [comment]
Fixed it.
