### ISSUE TITLE
hglpoint not working

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#93]
This endpoint is not working anymore

http://worldmap.harvard.edu/hglpoint/

Internal Server Error: /hglpoint/Traceback (most recent call last):

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "./geonode/proxy/views.py", line 195, in hglpoints
    title = node.getElementsByTagName('title')[0]

IndexError: list index out of range

**Comment by capooti** [comment]
@bglewis do we still need this?

**Comment by blewis** [comment]
no
