### ISSUE TITLE
User profiles cannot be edited

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#99]
When going to the "Edit Profile" page, a server 500 error is raised.

This is what is logged:

Internal Server Error: /profiles/edit/Traceback (most recent call last):

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "./geonode/profile/views.py", line 78, in edit_profile
    assert False

AssertionError

**Comment by capooti** [comment]
I cannot replicate this error in my development box.

The error is generated by the following line: https://github.com/cga-harvard/cga-worldmap/blob/worldmap-legacy/geonode/profile/views.py#L79

**Comment by capooti** [comment]
I tried to access to the profile from the shell in the production box, and it works:

>>> user = User.objects.filter(username='capooti')[0]
>>> profile = user.get_profile()
>>> print profile.name
capooti

so, apparently, it is request.user that cannot be resolved.
@mbertrand, @simod  and @ingenieroariel any idea here?

**Comment by capooti** [comment]
This is fixed.
For some reason in the production server there was this line just before the try block:

assert True
